version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: portalcapacitaciones-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: portalcapacitaciones-keycloak
    depends_on:
      - postgres
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: ${POSTGRES_USER:-postgres}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "8083:8080"

  usuarios-service:
    build:
      context: ../servicios/usuarios
    container_name: usuarios-service
    depends_on:
      - postgres
      - keycloak
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      USUARIOS_DB: usuarios_db
      JWT_SECRET: ${JWT_SECRET:-this-is-a-very-long-jwt-secret-string-please-change}
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL:-http://keycloak:8080}
      KEYCLOAK_PUBLIC_URL: ${KEYCLOAK_PUBLIC_URL:-http://localhost:8083}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-portal}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_USUARIOS_CLIENT_ID:-portal-usuarios}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_USUARIOS_CLIENT_SECRET:-usuarios-secret}
      KEYCLOAK_CLIENT_SCOPES: ${KEYCLOAK_CLIENT_SCOPES:-openid,profile,email}
    ports:
      - "8081:8081"

  cursos-service:
    build:
      context: ../servicios/cursos
    container_name: cursos-service
    depends_on:
      - postgres
      - usuarios-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      CURSOS_DB: cursos_db
      JWT_SECRET: ${JWT_SECRET:-this-is-a-very-long-jwt-secret-string-please-change}
    ports:
      - "8082:8082"

  apigateway:
    build:
      context: ../servicios/apigateway
    container_name: apigateway-service
    depends_on:
      - usuarios-service
      - cursos-service
    environment:
      USUARIOS_SERVICE_URI: http://usuarios-service:8081
      CURSOS_SERVICE_URI: http://cursos-service:8082
      JWT_SECRET: ${JWT_SECRET:-this-is-a-very-long-jwt-secret-string-please-change}
      KEYCLOAK_PUBLIC_URL: ${KEYCLOAK_PUBLIC_URL:-http://localhost:8083}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
      args:
        VITE_API_BASE: http://localhost:8080
    container_name: portal-frontend
    depends_on:
      - apigateway
    ports:
      - "8084:80"

volumes:
  postgres_data:
  keycloak_data:
